---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
  labels:
    name: mysql-db-pod
    app: python-todo-demo
spec:
  containers:
    - name: mysql-db
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test"
        - name: MYSQL_USER
          value: "test"
        - name: MYSQL_PASSWORD
          value: "test"
        - name: MYSQL_DATABASE
          value: "test"
