---
apiVersion: v1
kind: Service
metadata:
  name: python-todo-app
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 30005
  selector:
    name: python-todo-app-pod
    app: python-todo-demo
