---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 30005
  selector:
    app: python-todo-demo
    type: app
