---
- name: Install Java on bastion_host
  hosts: bastion_host
  become: true
  tasks:
    - name: Update package cache (recommended before installing)
      apt:
        update_cache: yes

    - name: Install java-17-amazon-corretto package
      apt:
        name: openjdk-11-jdk
        state: present

- name: Add Jenkins agents
  hosts: localhost
  # TODO: Change all the values to its correct values from your setup.
  vars:
    jenkins_url: "http://<jenkins-demo public ip or dns>:8080"
    jenkins_user: "pcc-devops"
    jenkins_token: "115a9dc50e7693500b175128f261b5653d"
    jenkins_cli_path: "~/jenkins-cli.jar"
    agents:
      - name: "bastion_host"
        host: "<public ip address of bastion_host>"
  tasks:
    - name: Download Jenkins CLI
      get_url:
        url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
        dest: /home/pcc-devops/jenkins-cli.jar
        mode: 0755

    - name: Generate agent XML configuration
      set_fact:
        agent_config: |
          <slave>
            <name>{{ item.name }}</name>
            <description></description>
            <remoteFS>/home/ubuntu</remoteFS>
            <numExecutors>1</numExecutors>
            <mode>NORMAL</mode>
            <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
            <launcher class="hudson.plugins.sshslaves.SSHLauncher" plugin="ssh-slaves@2.973.v0fa_8c0dea_f9f">
              <host>{{ item.host }}</host>
              <port>22</port>
              <credentialsId>ubuntu</credentialsId>
              <launchTimeoutSeconds>60</launchTimeoutSeconds>
              <maxNumRetries>10</maxNumRetries>
              <retryWaitTime>15</retryWaitTime>
              <sshHostKeyVerificationStrategy class="hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy"/>
              <tcpNoDelay>true</tcpNoDelay>
            </launcher>
            <label>{{ label }}</label>
            <nodeProperties>
              <hudson.node__monitors.DiskSpaceMonitorNodeProperty>
                <freeDiskSpaceThreshold>0</freeDiskSpaceThreshold>
                <freeTempSpaceThreshold>0</freeTempSpaceThreshold>
                <freeDiskSpaceWarningThreshold>0</freeDiskSpaceWarningThreshold>
                <freeTempSpaceWarningThreshold>0</freeTempSpaceWarningThreshold>
              </hudson.node__monitors.DiskSpaceMonitorNodeProperty>
            </nodeProperties>
          </slave>
      loop: "{{ agents }}"
      vars:
        label: "bastion_host"
      register: agent_configs

    - name: Create directory /tmp if it doesn't exist
      file:
        path: ./tmp
        state: directory
        mode: 0755

    - name: Create agent configuration files
      copy:
        content: "{{ item.ansible_facts.agent_config }}"
        dest: "./tmp/{{ item.item.name }}.xml"
      loop: "{{ agent_configs.results }}"
      loop_control:
        label: "{{ item.item.name }}"

    - name: Add Jenkins agents using CLI
      shell: |
        java -jar {{ jenkins_cli_path }} -s {{ jenkins_url }} -auth {{ jenkins_user }}:{{ jenkins_token }} create-node < ./tmp/{{ item.name }}.xml
      loop: "{{ agents }}"
