---
- name: Setup kubeadm
  hosts: localhost
  become: true

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Download kubernetes public signing key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present

    - name: Install k8s apt sources
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
        state: present

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name:
          - kubectl
        state: present

    - name: Hold kubectl packages
      dpkg_selections:
        name: kubectl
        selection: hold