---
- name: Setup kubeadm
  hosts: localhost
  become: true

  vars:
    kubernetes_version: "1.23.17"

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Download Google Cloud public signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Install k8s apt sources
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /
        state: present


    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - "kubectl={{ kubernetes_version }}"
        state: present

    - name: Hold kubelet, kubeadm, and kubectl packages
      apt:
        name:
          - kubectl
        state: hold