---
- name: Setup kubeadm
  hosts: localhost
  become: true

  vars:
    kubernetes_version: "1.24.0-00"

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Download Google Cloud public signing key
      shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

    - name: Add Kubernetes apt repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - "kubelet={{ kubernetes_version }}"
          - "kubeadm={{ kubernetes_version }}"
          - "kubectl={{ kubernetes_version }}"
        state: present

    - name: Hold kubelet, kubeadm, and kubectl packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: hold