---
- name: Copy kubeconfig to worker node
  hosts: workers
  tasks:
    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copy kubeconfig content from master
      copy:
        content: "{{ master_node_registers.kubeconfig_content }}"
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu

    - name: Join worker node to the cluster
      shell: "{{ master_node_registers.join_command }}"

