---
- name: Setup Kubernetes master node and install Weave Net
  hosts: master
  become: true
  vars:
    weave_net_url: "https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s-1.11.yaml"
  tasks:
    - name: Initialize Kubernetes master node
      shell: kubeadm init
      register: kubeadm_init

    - name: Copy join command to a fact
      set_fact:
        join_command: >
          {{
            kubeadm_init.stdout_lines |
            select('search', 'kubeadm join') |
            list |
            join(' ') +
            kubeadm_init.stdout_lines |
            select('search', '--discovery-token-ca-cert-hash') |
            first |
            regex_replace('\\n|\\t|\\\\', '')
          }}

    - name: Join command
      debug:
        msg: "{{ join_command }}"

    - name: Apply Weave Net network plugin
      shell: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f "{{ weave_net_url }}"

    - name: Prepare kubeconfig for workers
      slurp:
        src: /etc/kubernetes/admin.conf
      register: kubeconfig_content