---
- name: Copy kubeconfig to worker node
  hosts: workers
  become: yes
  tasks:
    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copy kubeconfig content from master
      copy:
        content: "{{ hostvars['master-node'].kubeconfig_content }}"
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu

    - name: Build the filtered command
      set_fact:
        filtered_command: "{{ hostvars['master-node'].join_command | regex_replace('\n|\t|\\', '') }}"

    - name: Join worker node to the cluster
      shell: "{{ filtered_command }}"

